language: python
python:
    - "3.8"
# command to install dependencies
install:
    - pip install flask
    - pip install flask_restfull
    - pip install mysql.connector
virtualenv:
  system_site_packages: true
# command to run tests
script: pytestm
