language: python
python:
    - "3.8"
# command to install dependencies
install:
    - pip install flask
    - pip install flask_restful
    - pip install mysql.connector
    - pip install gunicorn
# command to run tests
script:
    - cd department-app/
    - gunicorn --bind 127.0.0.1:5000 wsgi:app
    - python -m unittest tests/test_rest.py -v